name: Memo
description: An education platform to help high school students learn.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  sqflite: ^2.3.0
  sqflite_common_ffi: any #added this dependency to resolve databaseFactory not initialized in windows
  cupertino_icons: ^1.0.6
  percent_indicator: ^4.2.3
  responsive_framework: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/flashcards.json


